version: '3.0'
services:
  ldap:
    image: osixia/openldap:1.4.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=CodeZenith Consulting e.U.
      - LDAP_DOMAIN=codezenith.com
      - LDAP_ADMIN_PASSWORD=JohnSn0w
      #- DOCKER_ON_RUN=ldapadd -x -H ldap://localhost -b dc=codezenith,dc=com -D "cn=config" -W -f /tmp/extensions/nis.ldif"
    volumes:
      - /tmp/ldap/:/var/lib/ldap/
      - /tmp/sldap/:/etc/ldap/slapd.d/
      - ./extensions/:/tmp/extensions/
    hostname: "codezenith.com" # used for TLS generation
    networks:
      main:
        ipv4_address: 172.16.238.10


  lui:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=172.16.238.10
    networks:
      main:
        ipv4_address: 172.16.238.5

networks:
    main:
      ipam:
        driver: default
        config:
          - subnet: "172.16.238.0/24"