version: '3.0'
services:
  ldap:
    image: osixia/openldap:1.4.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION="My Company"
      - LDAP_DOMAIN="my-company.com"
      - LDAP_ADMIN_PASSWORD="JonSn0w"
    volumes:
      - /tmp/ldap_db/:/var/lib/ldap/
      - /tmp/ldap_conf/:/etc/ldap/slapd.d/
    hostname: "my-company.com" # used for TLS generation
    networks:
      main:
        ipv4_address: 172.16.238.10


  lui:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=172.16.238.10
    networks:
      - main

networks:
    main:
      ipam:
        driver: default
        config:
          - subnet: "172.16.238.0/24"